# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Raise pull requests for dependency updates against `develop`
    target-branch: "main"
    allow:
      - dependency-type: "development"
    # Include a list of updates with a notable prefix
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      # Note: The group order matters, since updates are assigned to the first matching group.
      dev-dependencies:
        dependency-type: "development"
