#
# Publishes the release to PyPI and docs to github pages
#

name: "publish release"

on: 
  release:
    types: [published]

jobs:
  build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: install build dependencies
        run: pip install wheel

      - name: build sdist
        run: python setup.py sdist

      - name: cache buildfiles
        uses: actions/cache@v2
        env:
          cache-name: cache-dist-files
        with:
          path: ./dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./dist/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build
            ${{ runner.os }}-

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: install doc build requirements
        run: pip install -r requirements-dev.txt -r requirements.txt

      - name: build docs
        run: cd docs && DJANGO_SETTINGS_MODULE=test.settings make html 

      - name: cache buildfiles
        uses: actions/cache@v2
        env:
          cache-name: cache-docs
        with:
          path: ./docs/build/html
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./docs/build/html/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build
            ${{ runner.os }}-

  publish-pypi:
    runs-on: ubuntu-latest
    needs: [build-source]
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish-gh-pages:
    needs: [build-docs]
    steps:
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
