#
# Publishes the release to PyPI and docs to github pages
#

name: DDA PyPI and docs release

on: 
  release:
    types: [created]

jobs:
  build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: python setup.py sdist

  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip install wheel
      - run: python setup.py bdist_wheel

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip install -r requirements-dev.txt -r requirements.txt
      - run: cd docs && DJANGO_SETTINGS_MODULE=test.settings make html 

  publish-pypi:
    needs: [build-source, build-wheel]
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      user: __token__
      password: ${{ secrets.PYPI_API_TOKEN }}

  publish-gh-pages:
    needs: [build-docs]
    uses: crazy-max/ghaction-github-pages@v2
    with:
      target_branch: gh-pages
      build_dir: docs/build/html
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
