name: unit-tests-and-static-analysis

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{ matrix.python-version }} Django ${{ matrix.django }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        make install
    - name: run tests
      run: |
        make test-all
